### ISSUE TITLE
Add exception for serverless scale event timeout SSL connection

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2-sdk-python#115]
In the past there have been no errors thrown for serverless scale event timeout.   With a new release of Senzing API, there is.  

With the old method, serverless scale event timeouts. were caught in this manner:

https://github.com/Senzing/redoer/blob/aedcf9824653f99965524d18b9606eb5ec31d817/redoer.py#L2074-L2078

But now that approach doesn't work:

```
2022-04-15 11:48:30.814 [sql:140686238566144:[40::MASTER:LOADER:]] ERR: Exception: 57P01FATAL:  terminating connection due to serverless scale event timeout
SSL connection has been closed unexpectedly
2022-04-15 11:48:30.814 [sql:140686238566144:[40::MASTER:LOADER:]] ERR: Statement: Statement: query = SELECT LAST_TOUCH_DT,LOCKING_ID FROM RES_ENT WHERE RES_ENT_ID=$1 and LENS_ID=$2
2022-04-15 11:48:30.814 [sql:140686238566144:[40::MASTER:LOADER:]] ERR: Bind Values: 7725827,1
2022-04-15 11:48:30.815 [sql:140686238566144:[40::MASTER:LOADER:]] ERR: Exception: no connection to the server
2022-04-15 11:48:30.815 [sql:140686238566144:[40::MASTER:LOADER:]] ERR: Statement: Statement: query = UPDATE OBS_ENT SET LAST_TOUCH_DT=$1,NODE_NAME=$2,LOCKING_ID=$3 WHERE OBS_ENT_ID=$4 AND LAST_TOUCH_DT=$5
2022-04-15 11:48:30.815 [sql:140686238566144:[40::MASTER:LOADER:]] ERR: Bind Values: 0,'loader-G2-engine',2,7725827,1650023304560
Exception in thread Process-0-ProcessReadFromSqsWithinfoThread-0:
Traceback (most recent call last):
  File "/app/redoer.py", line 2118, in process_redo_record
    self.g2_engine.processWithInfo(redo_record, info_bytearray, self.g2_engine_flags)
  File "/opt/senzing/g2/python/senzing/G2Engine.py", line 355, in processWithInfo
    raise TranslateG2ModuleException(tls_var.buf.value)
senzing.G2Exception.G2Exception: (G2Exception(...), "1007E|Database Connection Lost '(7:57P01FATAL:  terminating connection due to serverless scale event timeout SSL connection has been closed unexpectedly )'")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/app/redoer.py", line 2655, in run
    process_succeeded = self.process_redo_record(redo_record)
  File "/app/redoer.py", line 2129, in process_redo_record
    if is_db_connection_error(err.args[0]):
  File "/app/redoer.py", line 2996, in is_db_connection_error
    return 'Database Connection Failure' in errorText or 'Database Connection Lost' in errorText
TypeError: argument of type 'G2Exception' is not iterable
2022-04-15 11:55:37,548 senzing-50100723E Detected inactive thread. Total threads: 7  Active threads: 8
```

So to improve on this a new Exception needs to be added for a `1007E`.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/g2-sdk-python/pull/116
